import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const envLocalPath = path.join(rootDir, '.env.local');
const envPath = path.join(rootDir, '.env');

function generateSecret() {
  return crypto.randomBytes(32).toString('base64');
}

function updateEnvFile(filePath) {
  let content = '';
  if (fs.existsSync(filePath)) {
    content = fs.readFileSync(filePath, 'utf-8');
  }

  let updated = false;

  // Add AUTH_SECRET if not exists
  if (!content.includes('AUTH_SECRET=')) {
    const secret = generateSecret();
    content += `\n# Generated by setup-secrets.mjs\nAUTH_SECRET="${secret}"\n`;
    console.log(`✅ Added AUTH_SECRET to ${path.basename(filePath)}`);
    updated = true;
  } else {
    console.log(`ℹ️ AUTH_SECRET already exists in ${path.basename(filePath)}`);
  }

  // Set requested admin credentials if not set
  if (!content.includes('ADMIN_EMAIL=')) {
    content += `ADMIN_EMAIL="codingbullz@gmail.com"\n`;
    updated = true;
  }
  
  if (!content.includes('ADMIN_PASSWORD=')) {
    content += `ADMIN_PASSWORD="abc@1234567"\n`;
    updated = true;
  }
  
  if (!content.includes('ADMIN_NAME=')) {
    content += `ADMIN_NAME="bulladmin"\n`;
    updated = true;
  }

  // Ensure DATABASE_URL exists for local dev fallback
  if (!content.includes('DATABASE_URL=')) {
    content += `DATABASE_URL="postgresql://codingbull:change-me@127.0.0.1:5432/codingbull_website"\n`;
    console.log(`✅ Added fallback DATABASE_URL to ${path.basename(filePath)}`);
    updated = true;
  }

  if (updated) {
    fs.writeFileSync(filePath, content.trim() + '\n', 'utf-8');
    console.log(`🎉 Successfully updated ${path.basename(filePath)}`);
  }
}

console.log('Running secret setup...');
updateEnvFile(envLocalPath);

// Create .env if it doesn't exist to ensure prisma works easily
if (!fs.existsSync(envPath)) {
  fs.copyFileSync(envLocalPath, envPath);
  console.log('✅ Created .env from .env.local for Prisma');
} else {
  updateEnvFile(envPath);
}

console.log('Setup complete! You can now run `npx prisma migrate dev` and `npm run db:seed`.');
